name: CI

on:
  push:
    branches-ignore:
      - 'orig'
  pull_request:
    branches-ignore:
      - 'orig'

jobs:
  test:
    strategy:
      matrix:
        go: ['1.17', '1.16']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v2.4.0
    - name: Test
      run: go test -v -cover .